// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIaNWl9Ig8mGY19N0jJ2Bd_Z5b7RoaMCg',
    appId: '1:515116318903:web:14745705afe0fdd6668d32',
    messagingSenderId: '515116318903',
    projectId: 'fakey-waky',
    authDomain: 'fakey-waky.firebaseapp.com',
    storageBucket: 'fakey-waky.appspot.com',
    measurementId: 'G-CZMQYZM86J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYizCeNECgHfKq-nHakKKJ1qfciivMFyY',
    appId: '1:515116318903:android:d499357ac53fe26c668d32',
    messagingSenderId: '515116318903',
    projectId: 'fakey-waky',
    storageBucket: 'fakey-waky.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxTmshSUnhrp-cEkZmnr3X9GaBDkwn-B0',
    appId: '1:515116318903:ios:e7e1f87620efcb25668d32',
    messagingSenderId: '515116318903',
    projectId: 'fakey-waky',
    storageBucket: 'fakey-waky.appspot.com',
    iosClientId: '515116318903-999eh1p2emqq6841lpj8kfnkhvi8ilem.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxTmshSUnhrp-cEkZmnr3X9GaBDkwn-B0',
    appId: '1:515116318903:ios:e7e1f87620efcb25668d32',
    messagingSenderId: '515116318903',
    projectId: 'fakey-waky',
    storageBucket: 'fakey-waky.appspot.com',
    iosClientId: '515116318903-999eh1p2emqq6841lpj8kfnkhvi8ilem.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
